# Generated by Django 2.1.7 on 2019-07-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='股票代码')),
                ('name', models.CharField(max_length=32, verbose_name='公司名称')),
                ('ENUM_STOCK_TYPE', models.CharField(choices=[('sz', '深圳'), ('sh', '上海'), ('', '其他')], max_length=2, verbose_name='股票类型')),
                ('now', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='现价')),
                ('low', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='今日最低价')),
                ('high', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='今日最高价')),
                ('turnover', models.IntegerField(verbose_name='交易股数')),
                ('volume', models.FloatField(verbose_name='交易金额')),
                ('buy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='竞买价')),
                ('sell', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='竞卖价')),
                ('open', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='开盘价')),
                ('close', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='收盘价（昨天）')),
                ('datetime', models.DateTimeField(verbose_name='现在时间')),
                ('ask1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖一价')),
                ('ask1_volume', models.IntegerField(default=0, verbose_name='卖一量')),
                ('ask2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖二价')),
                ('ask2_volume', models.IntegerField(default=0, verbose_name='卖二量')),
                ('ask3', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖三价')),
                ('ask3_volume', models.IntegerField(default=0, verbose_name='卖三量')),
                ('ask4', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖四价')),
                ('ask4_volume', models.IntegerField(default=0, verbose_name='卖四量')),
                ('ask5', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖五价')),
                ('ask5_volume', models.IntegerField(default=0, verbose_name='卖五量')),
                ('bind1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买一价')),
                ('bind1_volume', models.IntegerField(default=0, verbose_name='买一量')),
                ('bind2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买二价')),
                ('bind2_volume', models.IntegerField(default=0, verbose_name='买二量')),
                ('bind3', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买三价')),
                ('bind3_volume', models.IntegerField(default=0, verbose_name='买三量')),
                ('bind4', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买四价')),
                ('bind4_volume', models.IntegerField(default=0, verbose_name='买四量')),
                ('bind5', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买五价')),
                ('bind5_volume', models.IntegerField(default=0, verbose_name='买五量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '股票',
                'verbose_name_plural': '股票',
            },
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=6, verbose_name='股票代码')),
                ('now', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='现价')),
                ('low', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='今日最低价')),
                ('high', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='今日最高价')),
                ('turnover', models.IntegerField(verbose_name='交易股数')),
                ('volume', models.FloatField(verbose_name='交易金额')),
                ('buy', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='竞买价')),
                ('sell', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='竞卖价')),
                ('datetime', models.DateTimeField(verbose_name='现在时间')),
                ('ask1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖一价')),
                ('ask1_volume', models.IntegerField(default=0, verbose_name='卖一量')),
                ('ask2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖二价')),
                ('ask2_volume', models.IntegerField(default=0, verbose_name='卖二量')),
                ('ask3', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖三价')),
                ('ask3_volume', models.IntegerField(default=0, verbose_name='卖三量')),
                ('ask4', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖四价')),
                ('ask4_volume', models.IntegerField(default=0, verbose_name='卖四量')),
                ('ask5', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='卖五价')),
                ('ask5_volume', models.IntegerField(default=0, verbose_name='卖五量')),
                ('bind1', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买一价')),
                ('bind1_volume', models.IntegerField(default=0, verbose_name='买一量')),
                ('bind2', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买二价')),
                ('bind2_volume', models.IntegerField(default=0, verbose_name='买二量')),
                ('bind3', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买三价')),
                ('bind3_volume', models.IntegerField(default=0, verbose_name='买三量')),
                ('bind4', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买四价')),
                ('bind4_volume', models.IntegerField(default=0, verbose_name='买四量')),
                ('bind5', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='买五价')),
                ('bind5_volume', models.IntegerField(default=0, verbose_name='买五量')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '股票历史',
                'verbose_name_plural': '股票历史',
            },
        ),
        migrations.CreateModel(
            name='StockRecommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=6, verbose_name='股票代码')),
                ('stock_name', models.CharField(max_length=32, verbose_name='公司名称')),
                ('strategy', models.CharField(max_length=32, verbose_name='策略')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '股票推荐',
                'verbose_name_plural': '股票推荐',
            },
        ),
    ]
