# Generated by Django 2.1.7 on 2019-07-06 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ENUM_STOCK_TYPE',
            new_name='enum_stock_type',
        ),
    ]
