# Generated by Django 2.1.7 on 2019-07-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190706_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buy',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='竞买价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='收盘价（昨天）'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='今日最高价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='今日最低价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='now',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='开盘价'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='竞卖价'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='buy',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='竞买价'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='high',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='今日最高价'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='low',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='今日最低价'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='now',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='现价'),
        ),
        migrations.AlterField(
            model_name='stockhistory',
            name='sell',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5, verbose_name='竞卖价'),
        ),
    ]
