# Generated by Django 2.2.1 on 2019-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190706_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockrecommend',
            name='latest',
            field=models.BooleanField(default=True, verbose_name='最新'),
        ),
    ]
